/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    // Clerk Authentication Keys
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    
    // Clerk API Configuration
    CLERK_API_URL: process.env.CLERK_API_URL,
    CLERK_API_VERSION: process.env.CLERK_API_VERSION,
    NEXT_PUBLIC_CLERK_API_VERSION: process.env.NEXT_PUBLIC_CLERK_API_VERSION,
    NEXT_PUBLIC_CLERK_JS: process.env.NEXT_PUBLIC_CLERK_JS,
    
    // Clerk URL Configuration
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_REDIRECT_URL: process.env.NEXT_PUBLIC_CLERK_REDIRECT_URL,
    NEXT_PUBLIC_CLERK_FALLBACK_REDIRECT_URL: process.env.NEXT_PUBLIC_CLERK_FALLBACK_REDIRECT_URL,
    
    // Clerk CORS Configuration
    CLERK_CORS_ALLOWED_ORIGINS: process.env.CLERK_CORS_ALLOWED_ORIGINS,
    CLERK_WEBHOOK_URL_VERIFICATION_ENABLED: process.env.CLERK_WEBHOOK_URL_VERIFICATION_ENABLED
  }
}

module.exports = nextConfig